### ISSUE TITLE
Upgrade to 6.1.5

### ISSUE THREAD

**Issue by ethikz** [jaeming/jeet-rails#10]
Can you upgrade to Jeet 6.1.5 and update dependencies?

**Comment by jaeming** [comment]
I have updated. The rubygems.org update will pull through later tonight. In the meanwhile you can link directly to the repo for the most up to date: 
`gem 'jeet', :git => 'https://github.com/jaeming/jeet-rails.git'`

**Comment by jaeming** [comment]
Update is now live on rubygems.org.
you can now regularly use `gem 'jeet'` in your Gemfile and make use of 6.1.5

**Comment by ethikz** [comment]
@jaeming Thanks!!
