### ISSUE TITLE
Gem 6.1.x not working

### ISSUE THREAD

**Issue by jhonnymoreira** [jaeming/jeet-rails#6]
I've been trying to use the most recent version of Jeet w/ SASS, but I'm always getting error saying `File to import not found or unreadable...` and pointing out the line 2 off **`application.scss`**.
```scss
@import "bourbon";
@import "jeet";
...
```

My **`Gemfile`** looks like this:
```ruby
...
gem 'jeet'
...
```

And the **`Gemfile.lock`** after `bundle install`:
```ruby
...
    jeet (6.1.2)
      sass (~> 3.2)
...
```

There is this Pull Request trying to update to version 6.1.2 create in January, but it wasn't closed yet: https://github.com/corysimmons/jeet-rails/pull/4

**Comment by corysimmons** [comment]
Sorry about that. I must have forgotten to merge that.

I've merged it now. I'm not sure if I need to update the Gem with RubyGems.org or what. Let me know if it works for you now or if there's something else I need to do.

**Comment by corysimmons** [comment]
@samccone Do you want me to transfer this repo over to you guys? I'd prefer not to maintain it.

**Comment by jhonnymoreira** [comment]
I'll test it as soon as possible. Thank you [=

**Comment by jhonnymoreira** [comment]
@corysimmons I've tried yesterday and today, but the version 6.1.2 of the Gem (Source: RubyGems) sadly keeps throwing me the same error. The stable version that I'm using is the 6.0.0.

**Comment by corysimmons** [comment]
@jhonnymoreira Have you tried it without `@import 'bourbon'`? Like... just Jeet and nothing else? The 2 libs might have a conflict?

**Comment by jhonnymoreira** [comment]
@corysimmons I can try to see if it works, but Jeet conflicting with Bourbon would be very bad, since Bourbon is extremely useful in general ways.

**Comment by corysimmons** [comment]
I agree it would be bad. I'd just like to narrow down the problem.

**Comment by jhonnymoreira** [comment]
@corysimmons Sorry for taking so long to reply. I've been using the Bower version of Jeet, instead of the gem. I'll test without Bourbon and then give you a heads up.

**Comment by corysimmons** [comment]
@jhonnymoreira Thanks I appreciate it. Sorry this doesn't work as expected. I don't really use Jeet + Rails very often so I'm not used to it.

**Comment by zstrenfel** [comment]
was this ever resolved? having the same problem

**Comment by corysimmons** [comment]
No. Happy to transfer this lib over to anyone who wants to maintain it. I don't work on Jeet anymore. My time is spent on [Lost](https://github.com/corysimmons/lost) nowadays.

**Comment by jaeming** [comment]
I had some similar issues and discovered the version from ruby gems has the wrong paths in jeet.scss:
@import '_settings';
@import '_functions';
@import '_grid';

where as the repo here is correct in:
@import 'jeet/_settings';
@import 'jeet/_functions';
@import 'jeet/_grid';

For those with similar issues, you can link directly to the github as a work-around:
gem 'jeet', :git => 'https://github.com/corysimmons/jeet-rails.git'

Also you could add jeet directly to vendor and @import in the application.scss as described here:
https://github.com/mojotech/jeet/tree/master/scss#rails-installation

**Comment by corysimmons** [comment]
Also happy to accept PRs to this.

**Comment by jaeming** [comment]
I don't think it needs a PR but rather a push to ruby gems. The ruby gems version is not current with the git repo...  Referencing ym gem from the git repo, I have no problems..

**Comment by corysimmons** [comment]
https://github.com/corysimmons/jeet-rails/issues/8

**Comment by jaeming** [comment]
The latest version has now been pushed to ruby gems which should fix this. If you've already installed, then run `bundle update --source jeet`
