### ISSUE TITLE
Undefined Mixin Center

### ISSUE THREAD

**Issue by echezbro** [jaeming/jeet-rails#7]
Any solution to this error?

Sass::SyntaxError at /
Undefined mixin 'center'.

Rails 4 App, following the file directory structure noted in the documentation.

**Comment by corysimmons** [comment]
https://github.com/corysimmons/jeet-rails/issues/8

**Comment by jaeming** [comment]
pulling the latest gem, 6.1.3 from ruby gems should fix this now.
