### ISSUE TITLE
Looking for a maintainer

### ISSUE THREAD

**Issue by corysimmons** [jaeming/jeet-rails#8]
I don't use Jeet or Rails anymore. If you're a cool person who likes to maintain stuff, please take over this project. :100:

**Comment by corysimmons** [comment]
I'll transfer repo and give you the gem.

**Comment by jaeming** [comment]
Hello,
I'm happy to maintain it if you'd like. I use it several projects and have several friends who use jeet as well now. Just let me know. :)

**Comment by corysimmons** [comment]
Awesome! What's your rubygems account so I can add you as an owner over there too?

**Comment by corysimmons** [comment]
Oh, you need to rename your current `jeet-rails` repo so I can transfer this one to you. :)

**Comment by jaeming** [comment]
renamed! and ruby gems is https://rubygems.org/profiles/jaeming

**Comment by corysimmons** [comment]
lol GitHub is making this difficult...

> jaeming already has a repository in the corysimmons/jeet-rails network

Maybe just download a zip of your jeet-rails then delete the dang thing?

**Comment by jaeming** [comment]
deleted!

**Comment by jaeming** [comment]
transfer complete. just need the ruby gems permissions.

**Comment by corysimmons** [comment]
@jaeming Whoops sorry. I think I added you to `jeet-rails` gem (super old gem) instead of `jeet`. You've been added to jeet now. Sorry about that. =)

**Comment by jaeming** [comment]
thanks! I'll check it out.

**Comment by corysimmons** [comment]
Awesome, again, thank you so much. =)
