### ISSUE TITLE
You can take the skull off the description now

### ISSUE THREAD

**Issue by corysimmons** [jaeming/jeet-rails#9]
![image](https://cloud.githubusercontent.com/assets/224636/12808596/04aa5ac2-cae6-11e5-8ae9-c456bf12de4d.png)

not a dead project anymore :)

**Comment by jaeming** [comment]
good call! lol. Removed.

**Comment by corysimmons** [comment]
Heck you might even want to add a "Now Maintained! :sparkles: " in there. :D
